name: latlong_to_osgrid
description: A dart package to translate given latitude and longitude coordinates into an 12 digit OS Grid Reference and vice versa.
version: 1.1.1
homepage: https://github.com/FunkyPenguin24/latlong_to_osgrid

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  vector_math: ^2.0.8
  test: '>=0.12.42 <2.0.0'
