name: latlong_to_osgrid
description: A dart package to translate given latitude and longitude coordinates into an 12 digit OS Grid Reference and vice versa.
version: 1.3.0
homepage: https://github.com/FunkyPenguin24/latlong_to_osgrid

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ^2.1.0
  test: ^1.16.8
